### ISSUE TITLE
Check if Pat-ID is reasonable value

### ISSUE THREAD

**Issue by pcvolkmer** [bzkf/obds-to-fhir#86]
Here:
https://github.com/bzkf/obds-to-fhir/blob/32cd649ca82e5c9ac45ffbed821f0ebc58d64e71/src/main/java/org/miracum/streams/ume/obdstofhir/mapper/ObdsConditionMapper.java#L78-L84

**Comment by jasminziegler** [comment]
z.B. Mindestlänge prüfen
prüfen, dass nicht nur "null" String drinsteht wie z.B. in Würzburg

**Comment by pcvolkmer** [comment]
Zu prüfen wäre:
* Kein `NULL`
* Mindestlänge 4-5 Zeichen
* Keine Zeichenkette `"null"`

Weitere Prüfungen könnten eine Log-Message verursachen - ohne Abbruch des Mappings.

Bei Mappen von `List<MeldungExport>` ist die Frage noch offen, wann abgebrochen werden soll:
* all or nothing?
* best effort - so gut es geht die `MeldungExport`, die verwendet werden können.

**Comment by MarcelErpi** [comment]
Als Ergänzung: Standortspezifische Id Layouts können über Regex-Ausdruck gematched und validiert werden. Hierfür muss dann dieser aber via einer Umgebungsvariable konfigurierbar sein. Ähnlich zu:
https://github.com/bzkf/obds-to-fhir/blob/32cd649ca82e5c9ac45ffbed821f0ebc58d64e71/src/main/java/org/miracum/streams/ume/obdstofhir/mapper/ObdsToFhirMapper.java#L65

**Comment by chgl** [comment]
Ich fänds auch perfekt wenn man das wirklich per konfigurierbarer regex machen kann - dann hat man die meiste Flexibilität. Default wäre dann ein match auf `\w*` (o.ä.).

**Comment by pcvolkmer** [comment]
Static method und Spring `@Value("{}")` - ohne static - ist so eine Sache. Da müsste sowas gemacht werden wie:

```java
class Klasse {
  private static Pattern pattern = Pattern.compile("\w*");

  @Value("${settings.patidpattern:\\w*}")
  public void setStringPattern(String value) {
    try {
      Klasse.pattern = Pattern.compile(value)
    } catch (Exception e) {
      log.error("Alles kaputt .... ", e);
      throw e;
    }
  }

  protected static String convertId(String id) {
    // ... pattern ...
  }
}
```

**Comment by pcvolkmer** [comment]
Im zugehörigen PR habe ich schon mal einen ersten Entwurf inklusive Test implementiert.

**Comment by pcvolkmer** [comment]
> Follow-Up Issue: wie gehen wir damit um, wenn PatID nicht valide ist? Exitstrategie --> keine Conditions usw erstellen; innerhalb der Condition wird ohnehin subject.reference gesetzt --> Abbruch;

Könnte als Exception realisiert werden, wie schon beim Umwandeln der oBDS-Datumsangaben in FHIR-Angaben. Dazu könnte eine eigene `PatientIdInvalidException` geworfen werden, die dann ähnlich der `DateTimeException` in `convertObdsDateToDateTimeType(String)` zu einen Abbruch führt.
